### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by jasp00** [jmechner/Prince-of-Persia-Apple-II#18]
How much would @ubisoftinc charge to release this project under a free software license?

**Comment by Zireael07** [comment]
This is Mechner's code, Ubisoft has nothing to do with it.

**Comment by jasp00** [comment]
`README.md` says:
> Ubisoft alone has the right to make and distribute Prince of Persia games.

**Comment by tooloudtoowide** [comment]
make and distribute - it means produce disk box and sell.

**Comment by jasp00** [comment]
It looks like we do not speak the same language, so...
how much would @jmechner charge to release this project under a free software license?

**Comment by adamgreen** [comment]
I get the feeling that the code was released as it was (including licensing terms or the lack thereof) for its historical and educational value only. As far as meeting those goals goes, it serves that job pretty well. 

I would only care about it having a more open license if I:
* Wanted to release my own variant of PoP based on the code and assets in this project. This however would violate Ubisoft's IP interest in PoP so it is explicitly disallowed in the README as mentioned above.
* Wanted to create a new Apple ][ game that has nothing to do with PoP but takes advantage of some of the Apple ][ assembly language code found in this repo. While there is no license on this project which explicitly allows this, I doubt that @jmechner would object to such usage.

**Comment by bam80** [comment]
So how about existing open-source reimplementations? Are they legal?

**Comment by cbmeeks** [comment]
@bam80 everything is legal until you get caught and/or sued by some giant, soulless corporation like Ubisoft.

**Comment by jasp00** [comment]
Corporations are run by workers, trusted by investors, and serving customers; they are quite a lot of souls. Commercial society and free software community can reach an understanding if there is a will.

**Comment by textfiles** [comment]
This is Jason Scott, who assisted Jordan Mechner is transferring the Prince of Persia source code and advocated it to be put on Github.

Our conversation about making it available on Github for the sake of history and research came down to he had long ago completely sold all rights to the name and content of Prince of Persia to Ubisoft. He is no longer able to grant any license related to the source code, so he is not likely to change this position years later.

As Ubisoft has no forum here to discuss financial or other considerations with Prince of Persia. I'd sugges contacting them, if you so choose. I am closing this issue.

**Comment by jasp00** [comment]
Then let us wait for @ubisoftinc to answer.

**Comment by jasp00** [comment]
> Then let us wait for @ubisoftinc to answer.

@brousseau-ubi, @belkiss, ping?
